---
name: Review new modules changes

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: tests

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: tests

      - uses: actions/github-script@v2
        if: ${{ always() }}
        with:
          script: |
            const output = `#### Terraform Initialization \`${{ steps.init.outcome }}\`
            #### Terraform Validation ${{ steps.validate.outputs.stdout }}

            actor: @${{ github.actor }}`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
